# Generated by Django 5.1.2 on 2024-10-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanager', '0003_alter_attendance_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-check_in'], 'permissions': [('can_view_attendance', 'Can view attendance'), ('can_edit_attendance', 'Can edit attendance'), ('can_delete_attendance', 'Can delete attendance')], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'permissions': [('can_view_department', 'Can view department'), ('can_edit_department', 'Can edit department'), ('can_delete_department', 'Can delete department')], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__username'], 'permissions': [('can_view_employee', 'Can view employee'), ('can_edit_employee', 'Can edit employee'), ('can_delete_employee', 'Can delete employee')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', 'start_date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
