# Generated by Django 5.1.2 on 2024-10-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanager', '0004_alter_attendance_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-check_in'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user__username'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
