# Generated by Django 5.1.2 on 2024-10-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanager', '0005_alter_attendance_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_tasks', to='staffmanager.employee'),
        ),
    ]
