# Generated by Django 5.1.1 on 2024-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerbook', '0002_author_publisher_remove_book_author_book_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
