# Generated by Django 5.1.1 on 2024-10-08 08:04

from django.db import migrations


class Migration(migrations.Migration):
    def create_initial_data(apps, schema_editor):
        User = apps.get_model('article_management', 'User')
        Author = apps.get_model('article_management', 'Author')
        Article = apps.get_model('article_management', 'Article')
        Comment = apps.get_model('article_management', 'Comment')

        user_a = User.objects.create_user(username='user_a', password='password123')
        user_b = User.objects.create_user(username='user_b', password='password123')
        
        author_a = Author.objects.create(user=user_a, bio='Author A bio')
        author_b = Author.objects.create(user=user_b, bio='Author B bio')

        article1 = Article.objects.create(
            title="First Article", 
            content="Content of the first article.", 
            author=author_a,
            image='articles/images/image1.jpg'  
        )
        article2 = Article.objects.create(
            title="Second Article", 
            content="Content of the second article.", 
            author=author_b,
            image='articles/images/image2.webp'  
        )

        Comment.objects.create(article=article1, user=user_a, content="Great article!")
        Comment.objects.create(article=article1, user=user_b, content="Thanks for sharing.")
        Comment.objects.create(article=article2, user=user_a, content="Nice insights!")
        
    dependencies = [
        ('article_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
