# Generated by Django 5.1.1 on 2024-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_management', '0003_auto_20241008_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/images/'),
        ),
    ]
